// <auto-generated />
using System;
using GestionLibrosBlazor.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionLibrosBlazor.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260927000435_AgregarRelacionPrestamoEstudiante")]
    partial class AgregarRelacionPrestamoEstudiante
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionLibrosBlazor.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("GestionLibrosBlazor.Models.Libros", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroId"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LibroId");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            AnioPublicacion = 1950,
                            Autor = "C.S Lewis",
                            Titulo = "Cronicas de Narnia"
                        },
                        new
                        {
                            LibroId = 2,
                            AnioPublicacion = 1999,
                            Autor = "Stephen Chbosky",
                            Titulo = "The perks of being a wallflower"
                        });
                });

            modelBuilder.Entity("GestionLibrosBlazor.Models.PrestamoLibro", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoId"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.HasKey("PrestamoId");

                    b.HasIndex("EstudianteId")
                        .IsUnique();

                    b.HasIndex("LibroId")
                        .IsUnique();

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("GestionLibrosBlazor.Models.PrestamoLibro", b =>
                {
                    b.HasOne("GestionLibrosBlazor.Models.Estudiantes", "Estudiantes")
                        .WithOne("Prestamo")
                        .HasForeignKey("GestionLibrosBlazor.Models.PrestamoLibro", "EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionLibrosBlazor.Models.Libros", "Libros")
                        .WithOne("Prestamo")
                        .HasForeignKey("GestionLibrosBlazor.Models.PrestamoLibro", "LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiantes");

                    b.Navigation("Libros");
                });

            modelBuilder.Entity("GestionLibrosBlazor.Models.Estudiantes", b =>
                {
                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("GestionLibrosBlazor.Models.Libros", b =>
                {
                    b.Navigation("Prestamo");
                });
#pragma warning restore 612, 618
        }
    }
}
